version: '2'
services:
  debug:
    container_name: debug #
    image: agileworks/sails_sample_env
    command: "/bin/sh"

    # expose:
    #   - "1338" #
    # ports:
    #   - "5001:5001"

    working_dir: /sailsSample
    volumes:
      - ./:/sailsSample
    depends_on:
      # - "e2e-env" #
    networks:
      - front-tier

  e2e-env:
    container_name: e2e-env
    image: selenium/standalone-firefox-debug:2.53.0
    # expose:
    #   - "4444" #
    ports:
      - "5900:5900" #
    networks:
      - front-tier #

  dev:
    container_name: sailsSample_dev
    image: agileworks/sails_sample_env
    command: "/bin/sh -l -c 'npm i && npm start'"

    ports:
      - "5001:5001"

    working_dir: /sailsSample
    volumes:
      - ./:/sailsSample
    depends_on:
      - "mysql"
    networks:
      - front-tier
      - back-tier

  mysql:
    container_name: mysql
    image: dgraziotin/mysql
    expose:
      - "3306"
    ports:
      - "3300:3306"

    environment:
      MYSQL_ADMIN_PASS: "root"
      MYSQL_USER_NAME: "nodejsSample"
      MYSQL_USER_DB: "nodejsSample"
      MYSQL_USER_PASS: "nodejsSample"
      CREATE_MYSQL_BASIC_USER_AND_DB: "true"

    volumes:
      - mysql-data:/var/lib/mysql/
    networks:
      - back-tier

  backup:
    image: ubuntu
    volumes:
      - ./:/backup
      - mysql-data:/dbdata
    command: "tar cvf /backup/backup.tar /dbdata"

  restore:
    image: ubuntu
    volumes:
      - ./:/backup
      - mysql-data:/dbdata
    working_dir: /dbdata
    command: "tar xvf /backup/backup.tar --strip 1"


volumes:
  mysql-data:
    driver: local

networks:
  front-tier:
    driver: bridge
  back-tier:
    driver: bridge
